### ISSUE TITLE
PypikaRepository can't be extended to support other db types

### ISSUE THREAD

**Issue by zznty** [lyz-code/repository-orm#104]
## Description
Currently we have `PypikaRepository` supporting just SQLlite with promised support for other types ([MySQL](#1), PostgreSQL),
but to add this support we will need to create dedicated repository classes such as `PostgreSqlRepository`, because combining everything into one class will result in tons of conditions and unnecessary complication of code.

## Possible Solutions
+ Rename current version of `PypikaRepository` to `SQLliteRepository`, but can result in code duplication for generic pypika operations.
+ Extract generic methods for pypika into `PypikaRepository` and create `SQLliteRepository` with SQLlite-related code

**Comment by lyz-code** [comment]
Hi @zznty thanks for taking the time to fill up an issue. Why do you think adding support for Mysql and Postgres will require to create tons of conditions and unnecessary complication of code? The only reason of using Pypika was that is a query builder that does all the translations required for the different databases.

**Comment by zznty** [comment]
for example you [have](https://github.com/lyz-code/repository-orm/blob/78bcd829868bfcac9f223efc4e3472e8b114abf2/src/repository_orm/adapters/data/pypika.py#L49) multiple code [fragments](https://github.com/lyz-code/repository-orm/blob/78bcd829868bfcac9f223efc4e3472e8b114abf2/src/repository_orm/adapters/data/pypika.py#L104) that wont work with other db types and will require something like this
```py
if db_type == "sqllite":
 ...
elif db_type == "mysql":
 ...
```

**Comment by lyz-code** [comment]
I see what you mean, so far I've only tested that it works with SQLite. Once we implement the tests of the other databases, we'll see if the changes are big enough to justify the need of another repository. 

If you want to contribute this feature, I'd say that you first start tweaking the `PypikaRepository` to make the other database work, and if we need we'll refactor it in a new class.

I'm closing this issue as I feel it's a duplicated of https://github.com/lyz-code/repository-orm/issues/1, specifically it's the discussion of it's implementation. If you want, we can continue the discussion there
