### ISSUE TITLE
mypy type error

### ISSUE THREAD

**Issue by ftaebi** [lyz-code/repository-orm#94]
First of all thanks for the very useful library. Here's my question:
I use an "Entity" class like this:
```python
class MyClass(Entity):
    foo: str
    ...
```
I want to `add` a list of MyClass objects like this:
```
repo.add(my_objs)
```
`my_objs` has the type `List[MyClass]`
This works perfectly but the problem is that surprisingly I get a mypy error:

`Value of type variable "EntityOrEntities" of "add" of "Repository" cannot be "List[MyClass]"`

Am I doing something wrong? How can I resolve this?

Thank you very much

**Comment by lyz-code** [comment]
Good day @ftaebi thanks for taking the time to open an issue and for using the library (you're the first user I'm aware of! `＼\ ٩( ᐛ )و /／` )

I'm aware of that error, but sadly I haven't found the way to fix it, after fighting for many hours with the type hints of the `add` method I gave up. There's [a note in the docs](https://lyz-code.github.io/repository-orm/repositories/#usage) that points to how to patch it. Sadly is with the addition of `# type: ignore` on the line that raises the error, I know that this is not ideal, I just hope that some python typing wizard comes and helps the package.

I valued the possibility of removing the functionality and only allow the addition of one instance, but I was sick of doing:

```python
for entity in entities:
    repo.add(entity)
```

So the least horrible solution is to add the ignore comment... Sorry!

If you have any idea on how to fix it or know someone that can chip in, please, please, please try to make a PR. The line of code that is creating the error is [this one](https://github.com/lyz-code/repository-orm/blob/master/src/repository_orm/adapters/data/abstract.py#L59) which is affected by [this TypeVar](https://github.com/lyz-code/repository-orm/blob/master/src/repository_orm/adapters/data/abstract.py#L15)

**Comment by ftaebi** [comment]
Hi, thanks for the quick reply. I think this library is fantastic actually. Unfortunately not many people know the repository pattern and 99% of python users are just interested in creating some code that seems to be doing what they think it should be doing somehow, which results in horrible code. So it doesn't surprise me that few people use this lib.
Regarding this typing problem: As haskell user I'm used to allways strictly type my code but unfortunately I'm not a mypy expert. I know some who are but those people are always on the brink of madness because of the many weird problems that occure.
Thanks for your support. For now I will just stick with `# type: ignore` and see if I can find some mypy expert.

**Comment by ftaebi** [comment]
Some nice guy sent me this:
The problem is that List is invariant. So `List[MyClass]` isn't a subtype of a `List[EntityModel]`. Either `EntityOrEntities = TypeVar("EntityOrEntities", List[EntityModel], EntityModel)` should be changed to `EntityOrEntities = TypeVar("EntityOrEntities", Sequence[EntityModel], EntityModel)`, with the downside that Sequence is not mutable, or the add method should be overloaded with two signatures: `add(self, entities: Entity, merge: bool = False) -> Entity` and `add(self, entities: List[Entity], merge: bool = False) -> List[Entity]`

**Comment by lyz-code** [comment]
Awesome! that's a huge tip, I'm diving [here](https://adamj.eu/tech/2021/05/29/python-type-hints-how-to-use-overload/), let's hope it works

**Comment by lyz-code** [comment]
@ftaebi it worked! you can try since `1.1.7`. You can't realize how thankful I'm right now that this issue is over.

**Comment by lyz-code** [comment]
Grrrr using `Entity` works, but not with subclasses of `Entity`, tomorrow I'll try with the `Sequence`

**Comment by lyz-code** [comment]
The problem was not with subclasses of entities, but with the result of functions that returned `List[Entity]`:

```python
def get_books() -> List[Book]:
    """Return some books."""
    return BookFactory.batch(5)


def test_add_works_with_return_value_of_function(repo_fake: FakeRepository) -> None:
    """
    Given: A Fake repository and a function that returns a list of entities
    When: Using repo.add on the result of the function
    Then: no mypy error is returned
    """
    books = get_books()

    result = repo_fake.add(books) # <-- mypy complained

    assert len(result) == 5
```

Since `1.1.8` this example also works, finally using the `Sequence` solution

**Comment by ftaebi** [comment]
Thank you very much. Great work.
